version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 5
- package-ecosystem: gomod
  directory: "test/workload"
  schedule:
    interval: "daily"
- package-ecosystem: gomod
  directory: "example/workload"
  schedule:
    interval: "daily"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule: 
   interval: daily
  open-pull-requests-limit: 5
