name: PR Build
on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Setup go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - name: Lint
        run: make lint
      - name: Test
        run: make test

  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Install regctl
        uses: regclient/actions/regctl-installer@bb562fac724b7b37c17f19671df07fe34fabc376 # main
      - name: Build image
        run: make docker-build
      - name: Export images
        run: tar -czvf images.tar.gz *-image.tar
      - name: Archive images
        uses: actions/upload-artifact@v7
        with:
          name: images
          path: images.tar.gz

  k8s-versions:
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    outputs:
      versions: ${{ steps.versions.outputs.versions }}

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Read Kubernetes versions
        id: versions
        run: echo "versions=$(jq -c '[.kubernetes[].version]' test/k8s-versions.json)" >> "$GITHUB_OUTPUT"

  integration-test:
    runs-on: ubuntu-22.04
    needs: [build, k8s-versions]

    permissions:
      contents: read

    strategy:
      fail-fast: false
      matrix:
        # The Kubernetes versions under test are listed in
        # test/k8s-versions.json. At a minimum, we should test the currently
        # supported versions of Kubernetes, but can go back farther as long as
        # we don't need heroics to pull it off (i.e. kubectl version juggling).
        k8s-version: ${{ fromJSON(needs.k8s-versions.outputs.versions) }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Install regctl
        uses: regclient/actions/regctl-installer@bb562fac724b7b37c17f19671df07fe34fabc376 # main
      - name: Download archived images
        uses: actions/download-artifact@v8
        with:
          name: images
          path: .
      - name: Load archived images
        run: |
          tar xvf images.tar.gz
          make load-images
      - name: Run integration tests
        run: K8S_VERSION=${{ matrix.k8s-version }} test/run.sh

  success:
    runs-on: ubuntu-22.04
    needs: [validate, integration-test]

    permissions:
      contents: read

    steps:
        - name: Declare victory!
          run: echo "# Successful" >> $GITHUB_STEP_SUMMARY
